feat: using the new first_block_height attribute from block meta
HathorNetwork/hathor-wallet-service pull request #58
Opened 2022-07-11 17:57 UTC by andreabadesso

### Acceptance Criteria
- We should use the `first_block_height` attribute from the transaction details instead of re-downloading the transaction to check what height confirmed it

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-07-12 17:56 UTC, r4mmer requested changes

2022-07-12 17:58 UTC, r4mmer commented on src/utils.ts
> +    if (firstBlockHeight == null) {
Another options would be to make `const firstBlockHeight = meta.first_block_height || null` then test with `=== null`

2022-07-12 18:14 UTC, andreabadesso commented on src/utils.ts
> +    if (firstBlockHeight == null) {
The problem with that would be on `meta.first_block_height === 0` that would default to null

2022-07-12 19:00 UTC, r4mmer commented on src/utils.ts
> +    if (firstBlockHeight == null) {
You're right, but we should at least change the `firstBlockHeight == null` to `===`

2022-07-12 19:07 UTC, r4mmer approved these changes

2022-07-12 20:06 UTC, luislhl commented on src/utils.ts
> +    // We need a fallback for old fullnodes as the first_block_height attribute was only introduced
Do we really need a fallback?

I mean, we are sure that the wallet-service's fullnode is on v0.49.0 already.

Unless someone else from the community is running the wallet-service-daemon out there, maybe we could even remove this fallback logic.

2022-07-12 20:06 UTC, luislhl approved these changes

2022-07-13 15:16 UTC, luislhl approved these changes

2022-07-13 15:47 UTC, r4mmer approved these changes

2022-07-13 15:47 UTC, merged